CREATE TABLE IF NOT EXISTS comments (
    ID BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    note_id BIGINT NOT NULL REFERENCES notes ON DELETE CASCADE,
    content TEXT NOT NULL,
    likes_count SMALLINT NOT NULL DEFAULT 0
)

