CREATE TABLE IF NOT EXISTS saves (
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    note_id BIGINT NOT NULL REFERENCES notes ON DELETE CASCADE,
    PRIMARY KEY(user_id, note_id)
);

