CREATE TABLE IF NOT EXISTS likes (
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,   
    note_id BIGINT NOT NULL REFERENCES notes ON DELETE CASCADE,
    PRIMARY KEY(user_id, note_id)
);

