name: Backend CI

on:
    push:
        paths:
            - "backend/***"

jobs:
    test-backend:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - uses: actions/checkout@v4

            # set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.25

              # build
            - name: Build
              run: |
                  cd backend
                  go build ./...

              # run tests
            - name: test
              run: |
                  cd backend
                  go test ./...
