name: Backend CI

on:
    push:
        paths:
            - "backend/**"

jobs:
    test-backend:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - uses: actions/checkout@v4

            # set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.25

            # install golangci-lint
            - name: install golangci-lint
              run: |
                  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

            # run linter
            - name: lint code
              run: ./bin/golangci-lint run

            # run tests
            - name: test
              run: |
                  cd backend
                  go test ./...
